### ISSUE TITLE
Fact Checking UI

### ISSUE THREAD

**Issue by subdavis** [TrumpTracker/trumptracker.github.io#2]
Hey!  I think the general UI implications for your fact checking could use work.

Each topic begins with a header that links to the source of the issues.  This is problematic because it implies that each issue set may be associated with at most 1 source.  In the event I want to pull policies from more than one article, there is no mechanism for doing this.

I recommend a more wikipedia-style citation structure.  That way each entry or issue can be associated with one or many sources.

Cheers!

**Comment by illepic** [comment]
Agreed. Each promise should be it's own data point, with relationships to multiple sources. For instance: "Build the wall" could be an entry with links to various urls clarifying and reiterating this promise in the various ways it was worded.

**Comment by VirenMohindra** [comment]
766352e8e7cb834b74da41f754998f94d01be4c6 should partly fix this issue. Just need to add it into the templating system to show it parses correctly.

**Comment by VirenMohindra** [comment]
commit 3666182d56af90a07a512e8b01af5ca99e867945 adds **main** source to each policy.

---

commit 78ff47ef5da96f193bc639f46984043adf19f612 adds citations to entire schema and displays first citation to each policy. -- NEEDS FIXING

The way I'm handling citations is by running through an array `citations` in `data.yaml` and displaying if **not empty**.

**Problem**: it works for the first citation source, but I haven't figured out how to increment the index # of the array so it can spit out the remaining citations. As seen in the picture below citation `1` and `2` both link to the same source because the array can't be incremented inside.

![screen shot 2016-11-20 at 11 21 48 pm](https://cloud.githubusercontent.com/assets/10460518/20470605/24a5e3ba-af78-11e6-8dfe-dadcb3664fda.jpg)

## Failed solutions, so people don't try these again:
`{{forloop.index}}` doesn't work inside an array

The hacky `{-1 | plus=1}` increment throws an error too
Source: http://stackoverflow.com/a/30305358/5673665

Assigning a variable 
`{% assign citationIndex = -1 %}` and using
`{{increment citationIndex}}` doesn't work either

paging @alanfriedman

**Comment by alanfriedman** [comment]
I can check it out shortly...

**Comment by illepic** [comment]
Noting here that I've addressed some of this in my recent PR: https://github.com/TrumpTracker/trumptracker.github.io/pull/66

**Comment by VirenMohindra** [comment]
In-Text Citations fully complete - 442ce1e113fc0ba87799220d7ad5b59574cf481e

thank you @illepic for your contribution.
