### ISSUE TITLE
Generalize for every governants and any country 

### ISSUE THREAD

**Issue by iltempe** [TrumpTracker/trumptracker.github.io#35]
Whath about to create a more generic repo to make monitoring in every country?

**Comment by VirenMohindra** [comment]
This issue doesn't apply to this repository -- also who will be tracking all the policies? 

I can create a generic repo and let users input the information, but tracking each and every policy made by every country would be pretty difficult.

**Comment by iltempe** [comment]
Sure. I was talking about have a "generic tool" not about tracking all the policies. In this way any country can use the tool for each tracking campaign. What do you think?

**Comment by alanfriedman** [comment]
I actually like this idea and had the same thought myself. Maybe fork this repo and create this issue there.

**Comment by rnewton** [comment]
I'm working on such a tool. https://github.com/politicalrev/accountability-api

The first target was more or less the same as this project. @VirenMohindra, how would you feel about consuming data from accountability-api as a build step? I haven't dug into the code to see how you're sourcing data now.

**Comment by VirenMohindra** [comment]
I can definitely see this API being implemented in the near future. I just checked out your repo - how are going to be able to let us view the data? We require a JavaScript API call since we're statically hosted on GitHub.

We're currently manually sourcing data, with contributions piping straight into a google excel sheet where I can review it. Then, I add it into `data/_data.json`.

**Comment by rnewton** [comment]
There are two options: 
1. Use ajax to talk to the API directly. `/politicians/donald-trump/promises` would be the endpoint to hit.
2. Using grunt/gulp/task-worker-of-your-choosing pull down the promises as a build step. You basically hit the endpoint to get the json and save it to `_data/promises.json` or something like that. 

1 has the advantage of always being up-to-date, but will be slower to load than a 100% static site. 2 has the advantage of leaving the site completely static (since the data is pulled at build-time), but will require a site rebuild anytime the data is updated (which could be automated). 

That API I wrote isn't actually hosted anywhere at the moment. It requires a feature to suggest and moderate promises for a politician. But when it is, I'd be delighted to have this project draw data from it since I was going to write my own front-end to that effect anyway.

**Comment by iltempe** [comment]
Wow! The point 2 for me should be nice. What should be done is use the api to produce data about politicians of the world. Is so difficult to generalize this project on the frontend part?

**Comment by rnewton** [comment]
I'm happy to help out with either approach if you would like. I won't have time to dedicate to this until the weekend, however. I'd also like to complete the API and start gathering some real data. 

My suggestion for generalizing the frontend would be to create a simple `_data/politicians.yml` (or whatever you want to call it) file that has all the politicians that you want to track. Then, create a layout/include that will loop over each of those and pull the data down from the api. It should create a new page on the built static site.

**Comment by VirenMohindra** [comment]
Maybe I understood @iltempe incorrectly - when I thought generic tool I was thinking more of a front-end. API would be great.

**Comment by iltempe** [comment]
@rnewton should be grate to have a config file to have a tool generic to track any other promises of other people in gov !

**Comment by VirenMohindra** [comment]
Populating one `.config` file and then having a separate `data.yaml` for policies would work for almost every politician! sounds good.

**Comment by MrLuit** [comment]
I really don't know. The whole site needs to be changed, a new subreddit for every politician, new images, etc

**Comment by VirenMohindra** [comment]
@MrLuit This won't be implemented on this https://trumptracker.github.io, maybe for another domain.

**Comment by MrLuit** [comment]
I would just advise people to fork and edit the site to your own politician.

**Comment by VirenMohindra** [comment]
Definitely.

Closing this issue since it doesn't apply to this repo. @rnewton pull request whenever you do manage to complete the API.

**Comment by iltempe** [comment]
@VirenMohindra I dont' understood your point. My point was to develop a generic idea starting from this but in another repo. Is not useful?

**Comment by VirenMohindra** [comment]
I'm definitely open to the generic repo idea but the reason I closed this issue on GitHub is because it doesn't serve this repo as of yet, if you look at the name of the project, trumptracker. 

Please feel free to fork this repository and make it generic, if you do manage to complete this and let us pipe data from a config I'll definitely try and implement this later on. 

As for now, this issue remains closed since we have more pressing issues to handle on the site

**Comment by iltempe** [comment]
@rnewton have you already forked in another repo this one?

**Comment by rnewton** [comment]
@iltempe I haven't. I need to finish the API before I think about the frontend. If you'd like to get started on a fork, https://github.com/johngeorgewright/grunt-http is a good starting point. Use grunt to hit the API or a mock API and then do the jekyll build. I'll update you (or anyone else interested) with the API url when it is deployed.

**Comment by rnewton** [comment]
I've deployed the API here: http://api.accountableto.us/api/politicians/donald-trump/promises (the data isn't 1:1 with the data here). I'll be working on adding some missing features and documentation before I fork.
