### ISSUE TITLE
Consider using prose.io for managing/editing data

### ISSUE THREAD

**Issue by patcon** [TrumpTracker/trumptracker.github.io#90]
Prose.io is a platform that was designed to offer a nice non-technical UI on top of the GitHub pull-request system, so that non-technical end-users could modify jekyll-based websites.

https://developmentseed.org/blog/2012/june/25/prose-a-content-editor-for-github/

It tries to run so that the client code interacts as closely as possible with the github api, and uses only the slimmest of gateways to coordinate user authorization.

There are two approaches to using Prose:

1. If you want to use it in it's stock form for content management, just add edit/submit links that point to the proper prose.io url, and users will get a nice form instead of needing to submit PRs or custom webforms. You can customize the prose form with [metadata in the project root](https://github.com/prose/prose/wiki/Prose-Configuration#metadata-configuration). This approach uses the **existing authorization gateway** hosted by the devs.

2. If you want the edit/create forms to be on your own jekyll site (ie. no links to prose.io urls for content management). This approach requires [**self-hosting your own "authorization gateway"**](https://github.com/prose/gatekeeper). A sample of this approach would be the [JKAN project](https://jkan.io).

**Comment by MrLuit** [comment]
I have looked into this and thought about the possibilities. 

I understand that it is easy for non-developers to edit the website, however, our database is stored in a YAML file which would be hard to edit for non-developers. The layout and other parts of the website are not meant to be edited and again not useful for non-developers. 

Even if we made a user-friendly interface to edit policies and create automatic pull request etc, I'm not sure that's how we want it to be. Because this website talks about a controversial topic, people will have different opinions regarding if policies have been completed or not. Therefore it could damage our reputation if we make the editing too easy.

**Comment by patcon** [comment]
ok, i'm not partial to PRs, but i would love to see something similar. I mostly talked up the tech side above, but imho the main criteria for an ideal process would:

- [x] allow non-technical citizens to submit new policy
  - Typeform seems to allow this
- [ ] allow non-technical citizens to engage in conversation *before* acceptance
  - PR's currently sometimes do this, but it seems any conversation is happening elsewhere (?)
- [x] allow non-technical citizens to engage in conversation *after* acceptance
  - reddit threads seem to allow this

(Not saying prose would have addressed all of the above, btw. In fact, it may have been a step back!)

Anyhow, this isn't a feature request, as I think the current process is a-ok for now, and working well! :) Just wanted to flag it for later, assuming that your tool starts getting generalized to other countries and jurisdictions

Thanks so much for this project and all your work! I appreciate y'all a whole lot :)
